export const componentKeymaps = {
  Button: ["Enter", "Space"],
  Input: ["Printable", "Tab"],
  Checkbox: ["Space"],
  Radio: ["Tab", "ArrowLeft", "ArrowRight", "ArrowUp", "ArrowDown"],
  Select: ["ArrowUp", "ArrowDown", "Enter"],
  Combobox: ["ArrowUp", "ArrowDown", "Enter", "Escape"],
  Autocomplete: ["ArrowUp", "ArrowDown", "Enter", "Escape", "Tab"],
  DatePicker: ["ArrowDown", "Enter", "Space", "Escape", "ArrowLeft", "ArrowRight", "PageUp", "PageDown"],
  DateRangePicker: ["ArrowDown", "Enter", "Space", "Escape", "ArrowLeft", "ArrowRight"],
  Dialog: ["Escape", "Tab", "Shift+Tab"],
  Tabs: ["ArrowLeft", "ArrowRight", "Home", "End", "Enter", "Space"],
  Menu: ["ArrowUp", "ArrowDown", "Escape", "Enter", "Space"],
  Toast: ["Escape", "Tab"],
} as const
